runtime: nodejs10
instance_class: F1
automatic_scaling:
  max_instances: 1
beta_settings: 
  cloud_sql_instances: [budget-app-259923:us-central1:budget-app]
env_variables:
  GCLOUD_STORAGE_BUCKET: budget-app-encrypted-secrets